# SPDX-FileCopyrightText: Copyright (c) 2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
docker:
  image: yegor256/ruby
assets:
  npmrc: yegor256/home#assets/npmrc
install: |
  sudo /usr/bin/install-node.sh
  npm install --no-color
  pdd -f /dev/null -v
release:
  pre: false
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i "s/0\.0\.0/${tag}/" package.json
    sed -i "s/0\.0\.0/${tag}/" src/version.js
    npm test --no-color
    git commit -am "set version to ${tag}"
    chmod 600 ../npmrc
    npm publish --access=public --no-color --userconfig=../npmrc
merge:
  script: |-
    npm test --no-color
