# SPDX-FileCopyrightText: Copyright (c) 2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: eslint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  eslint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run lint
